version: "3.7"
services:
  spark-master:
    image: spark-master:2.4.4
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
       - pyspark-files:/pyspark-files
    environment:
      - "SPARK_HOME=/spark"
      - "SPARK_LOCAL_IP=spark-master"
      - "PYSPARK_DRIVER_PYTHON=jupyter"
      - "PYSPARK_DRIVER_PYTHON_OPTS=notebook --allow-root --no-browser --ip 0.0.0.0"
  spark-worker-1:
    image: spark-worker:2.4.4
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env-spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
  spark-worker-2:
    image: spark-worker:2.4.4
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: ./env-spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - /mnt/spark-apps:/opt/spark-apps
       - /mnt/spark-data:/opt/spark-data
#  spark-worker-3:
#    image: spark-worker:2.4.4
#    container_name: spark-worker-3
#    hostname: spark-worker-3
#    depends_on:
#      - spark-master
#    ports:
#      - "8083:8081"
#    env_file: ./env-spark-worker.sh
#    environment:
#      - "SPARK_LOCAL_IP=spark-worker-3"
#    networks: 
#      spark-network:
#        ipv4_address: 10.5.0.5
#    volumes:
#       - /mnt/spark-apps:/opt/spark-apps
#       - /mnt/spark-data:/opt/spark-data
  
  mongo:
    image: mongo:latest
    restart: always
    container_name: 'mongo'
    hostname: mongodb
    ports:
      - '27017:27017'
    networks:
      spark-network:
        ipv4_address: 10.5.0.6
    volumes:
      - mongo-data:/data/db

networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
volumes:
  mongo-data:
  pyspark-files:
